{
 "title": "FastAPI & Kafka OTel Advanced",
 "tags": [
  "OpenTelemetry",
  "FastAPI",
  "Kafka"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(http_server_active_requests, service_name)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_client_messages_total{service_name=\"$service_name\"}, topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Messages Per Second (Throughput)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_client_messages_total{service_name=\"$service_name\", topic=~\"$topic\", direction=\"producer\"}[$__rate_interval]))",
     "legendFormat": "Produced: {{topic}}"
    },
    {
     "expr": "sum by (topic) (rate(kafka_client_messages_total{service_name=\"$service_name\", topic=~\"$topic\", direction=\"consumer\"}[$__rate_interval]))",
     "legendFormat": "Consumed: {{topic}}"
    }
   ]
  },
  {
   "title": "Average Message Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_client_message_size_bytes_sum{service_name=\"$service_name\", topic=~\"$topic\"}[$__rate_interval])) / sum by (topic) (rate(kafka_client_message_size_bytes_count{service_name=\"$service_name\", topic=~\"$topic\"}[$__rate_interval]))",
     "legendFormat": "Avg Size: {{topic}}"
    }
   ]
  },
  {
   "title": "Throttle RATE",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum by (direction, topic)(rate(kafka_client_throttle_time_ms_count{service_name=\"$service_name\", topic=~\"$topic\"}[$__rate_interval]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Time Lag (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, topic) (rate(kafka_client_message_lag_seconds_bucket{service_name=\"$service_name\", topic=~\"$topic\"}[$__rate_interval])))",
     "legendFormat": "Lag (P95): {{topic}}"
    }
   ]
  },
  {
   "title": "Average throttle time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum by (direction, topic )(rate(kafka_client_throttle_time_ms_sum{service_name=\"$service_name\", topic=~\"$topic\"}[$__rate_interval])\r\n/\r\nrate(kafka_client_throttle_time_ms_count{service_name=\"$service_name\", topic=~\"$topic\"}[$__rate_interval]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throttle % (percentage of calls throttled)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "sum by (direction, topic)((\r\n  rate(kafka_client_throttle_time_ms_count{service_name=\"$service_name\", topic=~\"$topic\"}[$__rate_interval])\r\n/\r\n  rate(kafka_client_messages_total{service_name=\"$service_name\", topic=~\"$topic\"}[$__rate_interval])\r\n) )\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (Process Duration)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, topic) (rate(kafka_client_duration_milliseconds_bucket{service_name=\"$service_name\", topic=~\"$topic\", direction=\"producer\"}[$__rate_interval])))",
     "legendFormat": "Produce Time (P95): {{topic}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le, topic) (rate(kafka_client_duration_milliseconds_bucket{service_name=\"$service_name\", topic=~\"$topic\", direction=\"consumer\"}[$__rate_interval])))",
     "legendFormat": "Consume Process Time (P95): {{topic}}"
    }
   ]
  },
  {
   "title": "Network Bandwidth (Bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_client_message_size_bytes_sum{service_name=\"$service_name\", topic=~\"$topic\"}[$__rate_interval]))",
     "legendFormat": "Bandwidth: {{topic}}"
    }
   ]
  },
  {
   "title": "Client Errors (Count)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (error_type) (increase(kafka_client_errors_total{service_name=\"$service_name\"}[$__rate_interval]))",
     "legendFormat": "{{error_type}}"
    }
   ]
  }
 ]
}