{
 "title": "FastAPI OpenTelemetry Metrics (Dynamic)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "label_values(http_server_duration_milliseconds_count, service_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Total per status code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (http_status_code) (increase(http_server_duration_milliseconds_count{service_name=\"$service_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors(RPS)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{http_status_code=~\"5..\", service_name=\"$service_name\"}[$__rate_interval]))",
     "legendFormat": "errors_rps"
    }
   ]
  },
  {
   "title": "Error(5xx)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(http_server_duration_milliseconds_count{service_name=\"$service_name\", http_status_code=~\"5..\"}[$__rate_interval])))\r\n",
     "legendFormat": "error_rate"
    }
   ]
  },
  {
   "title": "Total request ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(increase(http_server_duration_milliseconds_count{service_name=\"$service_name\"}[$__rate_interval])))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service_name=\"$service_name\"}[$__rate_interval]))",
     "legendFormat": "rps"
    }
   ]
  },
  {
   "title": "Requests per Second by Route",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (http_method,http_target) (rate(http_server_duration_milliseconds_count{service_name=\"$service_name\"}[$__rate_interval]))",
     "legendFormat": "{{http_method}} - {{http_target}}"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(http_server_active_requests{service_name=~\"$service_name\"})",
     "legendFormat": "active"
    }
   ]
  },
  {
   "title": "Requests per Second by Route/code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by (http_method,http_target,http_status_code) (\r\n  rate(\r\n    http_server_duration_milliseconds_count{\r\n      service_name=\"$service_name\"\r\n    }[$__rate_interval]\r\n  )\r\n)\r\n",
     "legendFormat": "{{http_method}} - {{http_target}} - {{http_status_code}}"
    }
   ]
  },
  {
   "title": "Request Latency (p50, p95, p99)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(http_server_duration_milliseconds_bucket{service_name=\"$service_name\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(http_server_duration_milliseconds_bucket{service_name=\"$service_name\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(http_server_duration_milliseconds_bucket{service_name=\"$service_name\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Request Breakdown by Route and Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by (http_method, http_route, http_target, http_status_code) (increase(http_server_duration_milliseconds_count{service_name=\"$service_name\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "filters": [
      { "id": "6247091a", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "query": "{nestedSetParent<0 && true && resource.service.name=\"$service_name\"} ",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Calls Correlation",
   "type": "nodeGraph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "limit": 20,
     "metricsQueryType": "range",
     "serviceMapQuery": "{server=\"fastapi-msc-test\"}",
     "tableType": "traces"
    }
   ]
  }
 ]
}