{
 "title": "Kafka Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "topic",
    "query": "label_values(kafka_topic_bytes_in_total, topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Bytes In per Topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_topic_bytes_in_total{topic=~\"$topic\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Partition Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(kafka_partition_count)" }
   ]
  },
  {
   "title": "Requests total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(kafka_request_count_total{ }[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Active Controller Count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_active_count)"
    }
   ]
  },
  {
   "title": "Bytes Out per Topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_topic_bytes_out_total{topic=~\"$topic\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Messages In per Topic",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 7 },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_topic_messages_in_total{topic=~\"$topic\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Log End Offset Ratio (per topic)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "avg by (topic) (kafka_log_end_offset_ratio{topic=~\"$topic\"})"
    }
   ]
  },
  {
   "title": "Network IO Bytes (Total)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_io_bytes_total[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Failed Requests per Topic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 14 },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_request_failed_total{topic=~\"$topic\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Consumer Fetch Throughput per topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_request_count_total{request=\"Fetch\", topic=~\"$topic\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Producer Throughput by Topic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by (topic) (rate(kafka_request_count_total{request=\"Produce\", topic=~\"$topic\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Under-Replicated Partitions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(kafka_under_replicated_partitions)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ISR Shrinks per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
   "targets": [
    {
     "expr": "rate(kafka_isr_shrinks_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumer Lag per Topicel",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum by (topic) (kafka_log_end_offset_ratio{topic=~\"$topic\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}