apiVersion: v1
kind: Namespace
metadata:
  name: applications
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-mfe-test-deployment
  namespace: applications
  labels:
    app: fastapi-mfe-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-mfe-test
  template:
    metadata:
      labels:
        app: fastapi-mfe-test
    spec:
      containers:
        - name: fastapi-mfe-test
          image: fastapi-mfe-test:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 512Mi
              cpu: 200m
            limits:
              memory: 1024Mi
              cpu: 500m

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-mfe-test-service
  namespace: applications
  labels:
    app: fastapi-mfe-test
spec:
  selector:
    app: fastapi-mfe-test
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fastapi-mfe-test-ingress
  namespace: applications
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /fastapi-mfe-test
            pathType: Prefix
            backend:
              service:
                name: fastapi-mfe-test-service
                port:
                  number: 8080
