{
 "title": "Kafka + JVM Observability (OTel Agent)",
 "tags": [
  "kafka",
  "otel",
  "jvm",
  "observability"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "label": "Service Name",
    "query": "label_values(kafka_message_count_total, service_name)"
   }
  ]
 },
 "panels": [
  { "title": "Kafka Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kafka Messages Throughput",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kafka_message_count_total{service_name=~\"$service\"})",
     "legendFormat": "Messages/sec"
    }
   ]
  },
  {
   "title": "Replication & Partition Health",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(kafka_partition_underReplicated{service_name=~\"$service\"})",
     "legendFormat": "Under-Replicated"
    },
    {
     "expr": "sum(kafka_partition_offline{service_name=~\"$service\"})",
     "legendFormat": "Offline"
    }
   ]
  },
  { "title": "Broker & Request Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Request Latency (P99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg(kafka_request_time_99p_milliseconds{service_name=~\"$service\"})\r\n",
     "legendFormat": "P99 Request Time"
    }
   ]
  },
  {
   "title": "Network I/O (bytes/sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(kafka_network_io_bytes_total{service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "Network I/O"
    }
   ]
  },
  { "title": "JVM Runtime Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "JVM Memory Used (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{service_name=~\"$service\"})",
     "legendFormat": "Used Memory"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "avg(jvm_thread_count{service_name=~\"$service\"})",
     "legendFormat": "Thread Count"
    }
   ]
  },
  {
   "title": "JVM Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"}) / sum(jvm_memory_max_bytes{area=\"heap\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_duration_seconds_sum{service_name=~\"$service\"}[$__rate_interval]))",
     "legendFormat": "GC Duration (s)"
    }
   ]
  }
 ]
}