# Dockerfile
FROM apache/kafka:latest

# -------------------------------
# Copy OpenTelemetry Javaagent & custom rules
# -------------------------------
COPY otel_javaagent/opentelemetry-javaagent.jar /opt/opentelemetry-javaagent.jar
COPY otel_javaagent/kafka-custom.yaml /opt/kafka-custom.yaml

# -------------------------------
# Set Kafka JVM options with modern OTel config
# -------------------------------
ENV KAFKA_OPTS="-javaagent:/opt/opentelemetry-javaagent.jar \
      -Dotel.instrumentation.jmx.enabled=true \
      -Dotel.instrumentation.jmx.config=file:/opt/kafka-custom.yaml \
      -Dotel.instrumentation.jmx.metric.interval=5000 \
      -Dotel.instrumentation.kafka-metrics.enabled=true \
      -Dotel.resource.attributes=service.name=kafka \
      -Dotel.exporter.otlp.endpoint=http://grafana-service.lgtm.svc.cluster.local:4318 \
      -Dotel.exporter.otlp.protocol=http/protobuf \
      -Dotel.metrics.exporter=otlp \
      -Dotel.traces.exporter=otlp \
      -Dotel.logs.exporter=otlp \
      -Dotel.metric.export.interval=5000 \
      -Dotel.javaagent.debug=true"

# -------------------------------
# Kafka default environment
# -------------------------------
ENV KAFKA_HEAP_OPTS="-Xms1g -Xmx1g"

# -------------------------------
# Entrypoint (Kafka server start)
# -------------------------------
ENTRYPOINT ["/bin/bash","-c","/usr/bin/dumb-init /opt/kafka/bin/kafka-server-start.sh /opt/kafka/config/server.properties"]
