apiVersion: v1
kind: Namespace
metadata:
  name: applications
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: applications
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: kafka:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: kafka
              containerPort: 9092
            - name: jmx
              containerPort: 9101
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: applications
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
    - name: jmx
      port: 9101
      targetPort: 9101
