apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  namespace: applications
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: kafka-otel:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: kafka
              containerPort: 9092
            - name: jmx
              containerPort: 7071
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: applications
  labels:
    app: kafka
spec:
  selector:
    app: kafka
  ports:
    - name: kafka
      port: 9092
      targetPort: 9092
    - name: jmx
      port: 7071
      targetPort: 7071
