apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: monitoring
  labels:
    app: lgtm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lgtm
  template:
    metadata:
      labels:
        app: lgtm
    spec:
      # K8s instrumentation
      serviceAccountName: lgtm-sa

      containers:
        - name: lgtm
          image: lgtm:1.0
          imagePullPolicy: IfNotPresent
#          readinessProbe:
#            tcpSocket:
#              port: 3000
#            initialDelaySeconds: 120 # Wait 120 seconds before starting the first check
#            periodSeconds: 10
#            timeoutSeconds: 5
          ports:
            - containerPort: 3000  # Grafana UI
              name: grafana
            - containerPort: 4318  # OTLP HTTP
              name: otlp-http
            - containerPort: 4317  # OTLP gRPC
              name: otlp-grpc
            - containerPort: 9090  # Prometheus endpoint
              name: prometheus
          resources:
            requests:
              memory: 1024Mi
              cpu: 1000m
            limits:
              memory: 5048Mi
              cpu: 3000m
          env:
            # --- K8s instrumentation ---
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_CLUSTER_NAME
              value: "kind"  # Set your cluster name

            # --- Grafana: Server settings (necessary to access via ingress controller ---
            - name: GF_SERVER_HTTP_ADDR
              value: "0.0.0.0"
            - name: GF_SERVER_ROOT_URL
              value: "%(protocol)s://%(domain)s:%(http_port)s/grafana"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
            - name: GF_SERVER_ENABLE_GZIP
              value: "true"
            # --- Enable / disable stack logs --- (ENABLE_LOGS_ALL, ENABLE_LOGS_LOKI,ENABLE_LOGS_PROMETHEUS,ENABLE_LOGS_TEMPO,ENABLE_LOGS_OTELCOL)
            - name: ENABLE_LOGS_ALL
              value: "false"
            # --- Disable noisy Grafana logs ---
            - name: GF_LOG_MODE
              value: "console"
            - name: GF_LOG_FILTERS
              value: "rendering:info"
          volumeMounts:
            # K8s instrumentation
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true

             # container original files location where will be replaces via config map referenced on volumes.
            - name: otelcol-config
              mountPath: /otel-lgtm/otelcol-config.yaml
              subPath: otelcol-config.yaml
#            - name: loki-config
#              mountPath: /otel-lgtm/loki-config.yaml
#              subPath: loki-config.yaml
#            - name: tempo-config
#              mountPath: /otel-lgtm/tempo-config.yaml
#              subPath: tempo-config.yaml
#            - name: prometheus-config
#              mountPath: /otel-lgtm/prometheus/prometheus.yml
#              subPath: prometheus.yml
      volumes:
        # K8s instrumentation
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers # Sometimes needed for symlinks
          hostPath:
            path: /var/lib/docker/containers

         # custom config of grafana lgtm that will be apply inside of container over original files.
        - name: otelcol-config
          configMap:
            name: otelcol-config
#        - name: prometheus-config4
#          configMap:
#            name: prometheus-config
#        - name: loki-config
#          configMap:
#            name: loki-config
#        - name: tempo-config
#          configMap:
#            name: tempo-config

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
spec:
  selector:
    app: lgtm
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: prometheus
      port: 9090
      targetPort: 9090

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana-service
                port:
                  number: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: otel-ingress
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /otel(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: grafana-service
                port:
                  number: 4318
          - path: /prometheus(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: grafana-service
                port:
                  number: 9090