apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: monitoring
  labels:
    app: lgtm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lgtm
  template:
    metadata:
      labels:
        app: lgtm
    spec:
      serviceAccountName: lgtm-sa
      containers:
        - name: lgtm
          image: lgtm:1.0
          imagePullPolicy: IfNotPresent
#          readinessProbe:
#            tcpSocket:
#              port: 3000
#            initialDelaySeconds: 120 # Wait 120 seconds before starting the first check
#            periodSeconds: 10
#            timeoutSeconds: 5
          ports:
            - containerPort: 3000  # Grafana UI
              name: grafana
            - containerPort: 4318  # OTLP HTTP
              name: otlp-http
            - containerPort: 4317  # OTLP gRPC
              name: otlp-grpc
            - containerPort: 9090  # Prometheus endpoint
              name: prometheus
          resources:
            requests:
              memory: 1024Mi
              cpu: 500m
            limits:
              memory: 2048Mi
              cpu: 1000m
          env:
            # --- K8s instrumentation ---
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: K8S_CLUSTER_NAME
              value: "kind"  # Set your cluster name

            # --- Grafana: Server settings (necessary to access via ingress controller ---
            - name: GF_SERVER_HTTP_ADDR
              value: "0.0.0.0"
            - name: GF_SERVER_ROOT_URL
              value: "%(protocol)s://%(domain)s:%(http_port)s/grafana"
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
            - name: GF_SERVER_ENABLE_GZIP
              value: "true"
            # --- Enable / disable stack logs ---
            - name: ENABLE_LOGS_ALL
              value: "false"   # Your latest value overrides previous "true"
            # --- Disable noisy Grafana logs ---
            - name: GF_LOG_MODE
              value: "console"
            - name: GF_LOG_FILTERS
              value: "rendering:info"
          volumeMounts:
            - name: otelcol-config
              mountPath: /otel-lgtm/otelcol-config.yaml
              subPath: otelcol-config.yaml
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
      # In your Pod/Deployment/DaemonSet spec
      volumes:
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers # Sometimes needed for symlinks
          hostPath:
            path: /var/lib/docker/containers
        - name: otelcol-config
          configMap:
            name: otelcol-config

---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
spec:
  selector:
    app: lgtm
  ports:
    - name: grafana
      port: 3000
      targetPort: 3000
    - name: otlp-http
      port: 4318
      targetPort: 4318
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
    - name: prometheus
      port: 9090
      targetPort: 9090

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  namespace: monitoring
#  annotations:
#    nginx.ingress.kubernetes.io/proxy-buffer-size: "8k"
#    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
#    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
#    nginx.ingress.kubernetes.io/configuration-snippet: |
#      proxy_set_header Host $host;
#      proxy_set_header X-Forwarded-Proto $scheme;
#      proxy_set_header X-Forwarded-Host $host;
#      proxy_set_header X-Forwarded-Prefix /grafana;
spec:
  ingressClassName: nginx
  rules:
    - host: localhost
      http:
        paths:
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana-service
                port:
                  number: 3000
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lgtm-sa
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lgtm-read-k8s
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
      - namespaces
      - services
      - endpoints
      - nodes/stats
      - nodes/proxy
      - nodes/metrics
    verbs: ["get", "list", "watch"]
  - apiGroups: [ "apps" ]
    resources: [ "deployments", "replicasets", "statefulsets", "daemonsets" ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lgtm-read-k8s-binding
roleRef:
  kind: ClusterRole
  name: lgtm-read-k8s
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: lgtm-sa
    namespace: monitoring