apiVersion: v1
kind: ServiceAccount
metadata:
  name: lgtm-sa
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lgtm-read-k8s
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
      - namespaces
      - services
      - endpoints
      - nodes/stats
      - nodes/proxy
      - nodes/metrics
    verbs: ["get", "list", "watch"]
  - apiGroups: [ "apps" ]
    resources: [ "deployments", "replicasets", "statefulsets", "daemonsets" ]
    verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lgtm-read-k8s-binding
roleRef:
  kind: ClusterRole
  name: lgtm-read-k8s
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: lgtm-sa
    namespace: monitoring